apiVersion: apps/v1
kind: Deployment
metadata:
  name: CatsAndDogs
  namespace: dev
spec:
  selector:
    matchLabels:
      app: CatsAndDogs
  replicas: 1
  template:
    metadata:
      labels:
        app: CatsAndDogs
    spec:
      containers:
      - name: CatsAndDogs
        image: lorenzoedoardofrancesco/catsanddogs:v1
        ports:
        - containerPort: 80
