apiVersion: v1
kind: Service
metadata:
  name: catsanddogsgenerator-service
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: catsanddogsgenerator
