apiVersion: v1
kind: Service
metadata:
  name: CatsAndDogs-service
  namespace: dev
spec:
  selector:
    app: CatsAndDogs
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 80
    nodePort: 30001
  type: NodePort
